# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='registry_service.proto',
  package='messaging.rpc.providers.grpc.proto.registry_service',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16registry_service.proto\x12\x33messaging.rpc.providers.grpc.proto.registry_service\x1a\x0emessages.proto2\xa6\x01\n\x0fRegistryService\x12\x92\x01\n\x13register_clock_node\x12<.messaging.rpc.providers.grpc.proto.RegisterClockNodeRequest\x1a=.messaging.rpc.providers.grpc.proto.RegisterClockNodeResponseb\x06proto3'
  ,
  dependencies=[messages__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REGISTRYSERVICE = _descriptor.ServiceDescriptor(
  name='RegistryService',
  full_name='messaging.rpc.providers.grpc.proto.registry_service.RegistryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=96,
  serialized_end=262,
  methods=[
  _descriptor.MethodDescriptor(
    name='register_clock_node',
    full_name='messaging.rpc.providers.grpc.proto.registry_service.RegistryService.register_clock_node',
    index=0,
    containing_service=None,
    input_type=messages__pb2._REGISTERCLOCKNODEREQUEST,
    output_type=messages__pb2._REGISTERCLOCKNODERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTRYSERVICE)

DESCRIPTOR.services_by_name['RegistryService'] = _REGISTRYSERVICE

# @@protoc_insertion_point(module_scope)
