# Generated by Django 3.0.7 on 2020-06-04 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('last_heatbeat', models.DateTimeField(auto_now_add=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Self',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('cluster_uuid', models.UUIDField(default=uuid.uuid4)),
                ('cluster_name', models.CharField(max_length=500)),
            ],
        ),
    ]
