# Generated by Django 3.0.7 on 2020-06-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_director', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Self',
            new_name='SchedulerDirector',
        ),
    ]
